#include "common.h"
#include "crypto_common.h"
#include <unistd.h>

#define FILENAME_SIZE 25
#define DIGEST_SIZE 32
#define BUFFER_SIZE 500

/* Help function for the usage of the program */ 
void help(char *program)
{
    fprintf (stdout, " This program generates a hash of a given message or file using SHA2\n");
    fprintf (stdout, " Usage %s [OPTIONS]\n", program);
    fprintf (stdout, "  -h help\t\tDisplays the help menu\n");
    fprintf (stdout, "  -f filename\t\tName of the file whose content will be used for generating the digest\n");
    fprintf (stdout, "  -t text\t\tText to process for generating the digest\n");
    fprintf (stdout, " Usage example: ./generate_hash -t \"Hello this is a test, the digest will be generated by processing all this information\"\n");

    exit (2);
}

/* Main program */
int main(int argc, char** argv)
{
    ATCA_STATUS status;
    ATCAIfaceCfg *gCfg = &cfg_ateccx08a_i2c_default;
    int c, text_flag = 0, file_flag = 0; 
    char text[BUFFER_SIZE] = "\0";
    char filename[FILENAME_SIZE] = "\0";
    char *file_digest;
    char text_digest[ATCA_SHA_DIGEST_SIZE];
    FILE *fp = NULL;

    while ((c = getopt (argc, argv, "f:t:h::")) != -1)
    {
        switch (c)
        {
            case 'h':
                help(argv[0]);
                break;
	    case 'f':
                strcpy(filename, optarg);
		file_flag = 1;
		break;
	    case 't':
		strcpy(text, optarg);
		text_flag = 1;
		break;
	    case '?':
		/* Check unkwnown options */
		if (optopt == 'f' || optopt == 't')
		{
                    fprintf(stderr, "Option -%c requires an argument\n", optopt);
		}
		return -2;
            default:
                fprintf(stderr, "Parameter not recognised: %c\n", c);
                fprintf(stderr, "Use argument -h for help\n");
		return -2;
	}
    }

    if ((text_flag && file_flag) || (text_flag == 0 && file_flag == 0) )
    {
        fprintf(stderr, "You need to include the text or file to generate the digest, check -h for help\n");
	return -2;
    }

    gCfg->atcai2c.bus=1;

    /* Creates a global ATCADevice object used by Basic API */
    status = atcab_init(gCfg);
    if (status != ATCA_SUCCESS)
    {
        fprintf(stderr, "Error initializing global ATCA Device\n");
        return -1;
    }
	
    if (file_flag)
    {
        fp = fopen(filename, "r");
        if (fp == NULL)
	{
            fprintf(stderr, "Error opening file %s\n", filename);
	    return -1;
	}

        /* Initializes SHA-256 calculation engine */
        status = atcab_sha_start();
        if (status != ATCA_SUCCESS)
        {
            fprintf(stderr, "Error starting sha engine\n");
	    return -1;
        }

	/* Generate hash of a file */
	file_digest = hash_file(fp);
        if (file_digest == NULL)
	{
            fprintf(stderr, "Error generating hash of file\n");
	    fclose(fp);
	    return -1;
	}
	
        fprintf(stdout, "The result hash of the file is: ");
	print_hex_to_file(file_digest, ATCA_SHA_DIGEST_SIZE, stdout);

        free(file_digest);
	fclose(fp);
    }
    else
    {
	/* Compute a SHA-256 digest of the given text */
        status = atcab_sha(strlen(text), text, text_digest);
	if (status != ATCA_SUCCESS)
	{
            fprintf(stderr, "Error generating sha-256 digest\n");
	    return -1;
	}

        fprintf(stdout, "The result hash of the given text is: ");
	print_hex_to_file(text_digest, ATCA_SHA_DIGEST_SIZE, stdout);
    }
	

    /* Release the global ATCADevice instance */
    status = atcab_release();
    if (status != ATCA_SUCCESS)
    {
        printf("Error releasing global ATCA Device\n");
        return -1;
    }

    return status;
}
